/** Catálogos Aduana (comext) usados en DTE exportación SII. */

/** Cláusula compra-venta (opción 03 / CodClauVenta). Fuente: http://comext.aduana.cl:7001/codigos/ */
export const CLAUSULAS_ADUANA: readonly { codigo: string; nombre: string }[] = [
  { codigo: "1", nombre: "CIF" },
  { codigo: "2", nombre: "CFR" },
  { codigo: "3", nombre: "EXW" },
  { codigo: "4", nombre: "FAS" },
  { codigo: "5", nombre: "FOB" },
  { codigo: "6", nombre: "S/CL" },
  { codigo: "7", nombre: "FCA" },
  { codigo: "8", nombre: "OTRA" },
  { codigo: "9", nombre: "DDP" },
  { codigo: "11", nombre: "CPT" },
  { codigo: "12", nombre: "CIP" },
  { codigo: "17", nombre: "DAT" },
  { codigo: "18", nombre: "DAP" },
];

/** Formas de pago Aduana (opción 07). Fuente: http://comext.aduana.cl:7001/codigos/ */
export const FORMAS_PAGO_ADUANA: readonly { codigo: string; nombre: string }[] = [
  { codigo: "1", nombre: "COB1" },
  { codigo: "2", nombre: "COBRANZA" },
  { codigo: "11", nombre: "ACRED" },
  { codigo: "12", nombre: "CBOF" },
  { codigo: "21", nombre: "S/PAGO" },
  { codigo: "32", nombre: "ANTICIPO" },
  { codigo: "50", nombre: "ANT/COB" },
  { codigo: "51", nombre: "ANT/COB" },
  { codigo: "52", nombre: "ANT/COB" },
  { codigo: "53", nombre: "ANT/COB" },
  { codigo: "54", nombre: "ANT/COB" },
  { codigo: "55", nombre: "ANT/COB" },
  { codigo: "56", nombre: "ANT/COB" },
  { codigo: "57", nombre: "ANT/COB" },
  { codigo: "58", nombre: "ANT/COB" },
  { codigo: "59", nombre: "ANT/COB" },
  { codigo: "60", nombre: "ANT/CRED" },
  { codigo: "61", nombre: "ANT/CRED" },
  { codigo: "62", nombre: "ANT/CRED" },
  { codigo: "63", nombre: "ANT/CRED" },
  { codigo: "64", nombre: "ANT/CRED" },
  { codigo: "65", nombre: "ANT/CRED" },
  { codigo: "66", nombre: "ANT/CRED" },
  { codigo: "67", nombre: "ANT/CRED" },
  { codigo: "68", nombre: "ANT/CRED" },
  { codigo: "69", nombre: "ANT/CRED" },
  { codigo: "70", nombre: "ANT/COB" },
  { codigo: "71", nombre: "ANT/COB" },
  { codigo: "72", nombre: "ANT/COB" },
  { codigo: "73", nombre: "ANT/COB" },
  { codigo: "74", nombre: "ANT/COB" },
  { codigo: "75", nombre: "ANT/COB" },
  { codigo: "80", nombre: "S/PAGO/COB" },
  { codigo: "81", nombre: "S/PAGO/COB" },
  { codigo: "82", nombre: "S/PAGO/COB" },
  { codigo: "83", nombre: "S/PAGO/COB" },
  { codigo: "84", nombre: "S/PAGO/COB" },
  { codigo: "85", nombre: "S/PAGO/COB" },
];

/** Monedas (opción 09 / TpoMoneda). Fuente: http://comext.aduana.cl:7001/codigos/ */
export const MONEDAS_ADUANA: readonly { codigo: string; nombre: string }[] = [
  { codigo: "1", nombre: "PESO AR" },
  { codigo: "4", nombre: "BOLIVIANO" },
  { codigo: "5", nombre: "REAL BR" },
  { codigo: "6", nombre: "DOLAR CAN" },
  { codigo: "13", nombre: "DOLAR USA" },
  { codigo: "23", nombre: "GUARANI" },
  { codigo: "24", nombre: "NUEVO SOL" },
  { codigo: "26", nombre: "PESO UY" },
  { codigo: "36", nombre: "DOLAR AUST" },
  { codigo: "48", nombre: "YUAN CN" },
  { codigo: "51", nombre: "CORONA DIN" },
  { codigo: "72", nombre: "YEN" },
  { codigo: "82", nombre: "FRANCO SZ" },
  { codigo: "96", nombre: "CORONA NOR" },
  { codigo: "97", nombre: "DOLAR NZ" },
  { codigo: "102", nombre: "LIBRA EST" },
  { codigo: "113", nombre: "CORONA SC" },
  { codigo: "127", nombre: "DOLAR HK" },
  { codigo: "128", nombre: "RAND" },
  { codigo: "129", nombre: "PESO CO" },
  { codigo: "132", nombre: "PESO MX" },
  { codigo: "134", nombre: "BOLIVAR" },
  { codigo: "136", nombre: "DOLAR SIN" },
  { codigo: "137", nombre: "RUPIA IN" },
  { codigo: "138", nombre: "DOLAR TAI" },
  { codigo: "139", nombre: "DIRHAM" },
  { codigo: "140", nombre: "WON KR" },
  { codigo: "141", nombre: "ZLOTY PL" },
  { codigo: "142", nombre: "EURO" },
  { codigo: "143", nombre: "CORONA CZ" },
  { codigo: "144", nombre: "FORINT HU" },
  { codigo: "145", nombre: "BAHT TH" },
  { codigo: "146", nombre: "LIRA TR" },
  { codigo: "147", nombre: "RINGGIT MY" },
  { codigo: "148", nombre: "RUBLO RU" },
  { codigo: "149", nombre: "RUPIA ID" },
  { codigo: "150", nombre: "HRYVNIA UA" },
  { codigo: "151", nombre: "SHEKEL IL" },
  { codigo: "152", nombre: "PESO PH" },
  { codigo: "153", nombre: "RIYAL SA" },
  { codigo: "154", nombre: "RUPIA PK" },
  { codigo: "155", nombre: "DONG VN" },
  { codigo: "156", nombre: "LIBRA EG" },
  { codigo: "157", nombre: "LEU RO" },
  { codigo: "158", nombre: "CORONA IS" },
  { codigo: "159", nombre: "RIAL IR" },
  { codigo: "160", nombre: "COLON CR" },
  { codigo: "161", nombre: "BALBOA PA" },
  { codigo: "200", nombre: "PESO CL" },
  { codigo: "900", nombre: "OTRAS MONEDAS" },
];

/** Países (opción 10 / CodPaisRecep-Destin). Fuente: http://comext.aduana.cl:7001/codigos/ */
export const PAISES_ADUANA: readonly { codigo: string; nombre: string }[] = [
  { codigo: "101", nombre: "SENEGAL" },
  { codigo: "102", nombre: "GAMBIA" },
  { codigo: "103", nombre: "GUINEA-BISSAU" },
  { codigo: "104", nombre: "GUINEA" },
  { codigo: "105", nombre: "SIERRA LEONA" },
  { codigo: "106", nombre: "LIBERIA" },
  { codigo: "107", nombre: "COSTA DE MARFIL" },
  { codigo: "108", nombre: "GHANA" },
  { codigo: "109", nombre: "TOGO" },
  { codigo: "111", nombre: "NIGERIA" },
  { codigo: "112", nombre: "SUDAFRICA" },
  { codigo: "113", nombre: "BOTSWANA" },
  { codigo: "114", nombre: "LESOTHO" },
  { codigo: "115", nombre: "MALAWI" },
  { codigo: "116", nombre: "ZIMBABWE" },
  { codigo: "117", nombre: "ZAMBIA" },
  { codigo: "118", nombre: "COMORAS" },
  { codigo: "119", nombre: "MAURICIO" },
  { codigo: "120", nombre: "MADAGASCAR" },
  { codigo: "121", nombre: "MOZAMBIQUE" },
  { codigo: "122", nombre: "SWAZILANDIA" },
  { codigo: "123", nombre: "SUDAN" },
  { codigo: "124", nombre: "EGIPTO" },
  { codigo: "125", nombre: "LIBIA" },
  { codigo: "126", nombre: "TUNEZ" },
  { codigo: "127", nombre: "ARGELIA" },
  { codigo: "128", nombre: "MARRUECOS" },
  { codigo: "129", nombre: "CABO VERDE" },
  { codigo: "130", nombre: "CHAD" },
  { codigo: "131", nombre: "NIGER" },
  { codigo: "133", nombre: "MALI" },
  { codigo: "134", nombre: "MAURITANIA" },
  { codigo: "135", nombre: "TANZANIA" },
  { codigo: "136", nombre: "UGANDA" },
  { codigo: "137", nombre: "KENIA" },
  { codigo: "138", nombre: "SOMALIA" },
  { codigo: "139", nombre: "ETIOPIA" },
  { codigo: "140", nombre: "ANGOLA" },
  { codigo: "141", nombre: "BURUNDI" },
  { codigo: "142", nombre: "RWANDA" },
  { codigo: "143", nombre: "REP.DEM. CONGO" },
  { codigo: "144", nombre: "CONGO" },
  { codigo: "145", nombre: "GABON" },
  { codigo: "146", nombre: "S.TOM.PRINCIPE" },
  { codigo: "147", nombre: "GUINEA ECUATRL" },
  { codigo: "148", nombre: "REP.CENT.AFRIC." },
  { codigo: "149", nombre: "CAMERUN" },
  { codigo: "150", nombre: "BENIN" },
  { codigo: "151", nombre: "TERR.BRIT.EN AF" },
  { codigo: "152", nombre: "TER.ESPAN.EN AF" },
  { codigo: "153", nombre: "TERR.FRAN.EN AF" },
  { codigo: "155", nombre: "DJIBOUTI" },
  { codigo: "156", nombre: "SEYCHELLES" },
  { codigo: "159", nombre: "NAMIBIA" },
  { codigo: "160", nombre: "SUDAN DEL SUR" },
  { codigo: "161", nombre: "BURKINA FASO" },
  { codigo: "163", nombre: "ERITREA" },
  { codigo: "164", nombre: "ISLAS MARSHALL" },
  { codigo: "165", nombre: "SAHARA OCCIDENT" },
  { codigo: "201", nombre: "VENEZUELA" },
  { codigo: "202", nombre: "COLOMBIA" },
  { codigo: "203", nombre: "TRINID.Y TOBAGO" },
  { codigo: "204", nombre: "BARBADOS" },
  { codigo: "205", nombre: "JAMAICA" },
  { codigo: "206", nombre: "REP.DOMINICANA" },
  { codigo: "207", nombre: "BAHAMAS" },
  { codigo: "208", nombre: "HAITI" },
  { codigo: "209", nombre: "CUBA" },
  { codigo: "210", nombre: "PANAMA" },
  { codigo: "211", nombre: "COSTA RICA" },
  { codigo: "212", nombre: "NICARAGUA" },
  { codigo: "213", nombre: "EL SALVADOR" },
  { codigo: "214", nombre: "HONDURAS" },
  { codigo: "215", nombre: "GUATEMALA" },
  { codigo: "216", nombre: "MEXICO" },
  { codigo: "217", nombre: "GUYANA" },
  { codigo: "218", nombre: "ECUADOR" },
  { codigo: "219", nombre: "PERU" },
  { codigo: "220", nombre: "BRASIL" },
  { codigo: "221", nombre: "BOLIVIA" },
  { codigo: "222", nombre: "PARAGUAY" },
  { codigo: "223", nombre: "URUGUAY" },
  { codigo: "224", nombre: "ARGENTINA" },
  { codigo: "225", nombre: "U.S.A." },
  { codigo: "226", nombre: "CANADA" },
  { codigo: "227", nombre: "TERR.BRIT.EN AM" },
  { codigo: "228", nombre: "TERR.FRAN.EN AM" },
  { codigo: "229", nombre: "TER.HOLAN.EN AM" },
  { codigo: "230", nombre: "TERR.D/DINAMARC" },
  { codigo: "231", nombre: "DOMINICA" },
  { codigo: "232", nombre: "GRANADA" },
  { codigo: "233", nombre: "SANTA LUCIA(ISL" },
  { codigo: "234", nombre: "S.VTE.Y GRANAD." },
  { codigo: "235", nombre: "SURINAM" },
  { codigo: "236", nombre: "BELICE" },
  { codigo: "240", nombre: "ANTIGUA Y BBUDA" },
  { codigo: "241", nombre: "SNT.KIT & NEVIS" },
  { codigo: "242", nombre: "ANGUILA" },
  { codigo: "243", nombre: "ARUBA" },
  { codigo: "244", nombre: "BERMUDAS" },
  { codigo: "245", nombre: "ISLAS VIRG.BRIT" },
  { codigo: "246", nombre: "ISLAS CAYMAN" },
  { codigo: "247", nombre: "ANTILLAS NEERLA" },
  { codigo: "248", nombre: "TURCAS Y CAICOS" },
  { codigo: "249", nombre: "ISLAS VIRG.EUA" },
  { codigo: "250", nombre: "MARTINICA" },
  { codigo: "251", nombre: "PUERTO RICO" },
  { codigo: "252", nombre: "MONSERRAT" },
  { codigo: "253", nombre: "GROENLADIA" },
  { codigo: "301", nombre: "JORDANIA" },
  { codigo: "302", nombre: "ARABIA SAUDITA" },
  { codigo: "303", nombre: "KUWAIT" },
  { codigo: "304", nombre: "OMAN" },
  { codigo: "305", nombre: "CHIPRE" },
  { codigo: "306", nombre: "ISRAEL" },
  { codigo: "307", nombre: "IRAK" },
  { codigo: "308", nombre: "AFGHANISTAN" },
  { codigo: "309", nombre: "IRAN" },
  { codigo: "310", nombre: "SIRIA" },
  { codigo: "311", nombre: "LIBANO" },
  { codigo: "312", nombre: "QATAR" },
  { codigo: "313", nombre: "BAHREIN" },
  { codigo: "314", nombre: "SRI LANKA" },
  { codigo: "315", nombre: "CAMBODIA" },
  { codigo: "316", nombre: "LAOS" },
  { codigo: "317", nombre: "INDIA" },
  { codigo: "318", nombre: "BUTAN" },
  { codigo: "319", nombre: "THAILANDIA" },
  { codigo: "320", nombre: "NEPAL" },
  { codigo: "321", nombre: "BANGLADESH" },
  { codigo: "322", nombre: "PALESTINA" },
  { codigo: "324", nombre: "PAKISTAN" },
  { codigo: "325", nombre: "VIETNAM" },
  { codigo: "326", nombre: "MYANMAR (EX BIR" },
  { codigo: "327", nombre: "ISLAS MALDIVAS" },
  { codigo: "328", nombre: "INDONESIA" },
  { codigo: "329", nombre: "MALASIA" },
  { codigo: "330", nombre: "TAIWAN (FORMOSA" },
  { codigo: "331", nombre: "JAPON" },
  { codigo: "332", nombre: "SINGAPUR" },
  { codigo: "333", nombre: "COREA DEL SUR" },
  { codigo: "334", nombre: "RPD COREA DEL N" },
  { codigo: "335", nombre: "FILIPINAS" },
  { codigo: "336", nombre: "CHINA" },
  { codigo: "337", nombre: "MONGOLIA" },
  { codigo: "341", nombre: "EMIR.ARAB.UNID." },
  { codigo: "342", nombre: "HONG KONG" },
  { codigo: "343", nombre: "TER.PORTUG.E/AS" },
  { codigo: "344", nombre: "BRUNEI" },
  { codigo: "345", nombre: "MACAO" },
  { codigo: "346", nombre: "REPUBLICA DE YE" },
  { codigo: "401", nombre: "FIJI" },
  { codigo: "402", nombre: "NAURU" },
  { codigo: "403", nombre: "ISLAS TONGA" },
  { codigo: "404", nombre: "SAMOA OCC." },
  { codigo: "405", nombre: "NUEVA ZELANDIA" },
  { codigo: "406", nombre: "AUSTRALIA" },
  { codigo: "407", nombre: "TERR.BRIT.EN OP" },
  { codigo: "408", nombre: "TERR.FRAN.EN OP" },
  { codigo: "409", nombre: "T.NORTEAM.EN OP" },
  { codigo: "412", nombre: "PPUA.NVA.GUINEA" },
  { codigo: "415", nombre: "VANUATU" },
  { codigo: "416", nombre: "KIRIBATI" },
  { codigo: "417", nombre: "MICRONESIA" },
  { codigo: "418", nombre: "ISLAS SALOMON" },
  { codigo: "419", nombre: "TUVALU" },
  { codigo: "420", nombre: "BELAU" },
  { codigo: "421", nombre: "NIUE" },
  { codigo: "422", nombre: "POLINESIA FRAN." },
  { codigo: "423", nombre: "NUEVA CALEDONIA" },
  { codigo: "424", nombre: "ISLAS MARIANAS" },
  { codigo: "425", nombre: "GUAM" },
  { codigo: "426", nombre: "TIMOR ORIENTAL" },
  { codigo: "427", nombre: "ISLAS COOK" },
  { codigo: "501", nombre: "PORTUGAL" },
  { codigo: "504", nombre: "ITALIA" },
  { codigo: "505", nombre: "FRANCIA" },
  { codigo: "506", nombre: "IRLANDA" },
  { codigo: "507", nombre: "DINAMARCA" },
  { codigo: "508", nombre: "SUIZA" },
  { codigo: "509", nombre: "AUSTRIA" },
  { codigo: "510", nombre: "REINO UNIDO" },
  { codigo: "511", nombre: "SUECIA" },
  { codigo: "512", nombre: "FINLANDIA" },
  { codigo: "513", nombre: "NORUEGA" },
  { codigo: "514", nombre: "BELGICA" },
  { codigo: "515", nombre: "PAISES BAJOS" },
  { codigo: "516", nombre: "ISLANDIA" },
  { codigo: "517", nombre: "ESPANA" },
  { codigo: "518", nombre: "ALBANIA" },
  { codigo: "519", nombre: "RUMANIA" },
  { codigo: "520", nombre: "GRECIA" },
  { codigo: "522", nombre: "TURQUIA" },
  { codigo: "523", nombre: "MALTA" },
  { codigo: "524", nombre: "SANTA SEDE" },
  { codigo: "525", nombre: "ANDORRA" },
  { codigo: "527", nombre: "BULGARIA" },
  { codigo: "528", nombre: "POLONIA" },
  { codigo: "530", nombre: "HUNGRIA" },
  { codigo: "532", nombre: "LUXEMBURGO" },
  { codigo: "534", nombre: "LIECHTENSTEIN" },
  { codigo: "535", nombre: "MONACO" },
  { codigo: "536", nombre: "SAN MARINO" },
  { codigo: "540", nombre: "ARMENIA" },
  { codigo: "541", nombre: "AZERBAIJAN" },
  { codigo: "542", nombre: "BELARUS" },
  { codigo: "543", nombre: "BOSNIA HEZGVINA" },
  { codigo: "544", nombre: "REPUBLICA CHECA" },
  { codigo: "545", nombre: "REP.ESLOVACA" },
  { codigo: "546", nombre: "REPUBLICA DE SE" },
  { codigo: "547", nombre: "CROACIA" },
  { codigo: "548", nombre: "ESLOVENIA" },
  { codigo: "549", nombre: "ESTONIA" },
  { codigo: "550", nombre: "GEORGIA (B)" },
  { codigo: "551", nombre: "KASAJSTAN" },
  { codigo: "552", nombre: "KIRGISTAN" },
  { codigo: "553", nombre: "LETONIA" },
  { codigo: "554", nombre: "LITUANIA" },
  { codigo: "555", nombre: "MACEDONIA" },
  { codigo: "556", nombre: "MOLDOVA" },
  { codigo: "557", nombre: "TADJIKISTAN" },
  { codigo: "558", nombre: "TURKMENISTAN" },
  { codigo: "559", nombre: "UCRANIA" },
  { codigo: "560", nombre: "UZBEKISTAN" },
  { codigo: "561", nombre: "MONTENEGRO" },
  { codigo: "562", nombre: "RUSIA" },
  { codigo: "563", nombre: "ALEMANIA" },
  { codigo: "565", nombre: "GIBRALTAR" },
  { codigo: "566", nombre: "GUERNSEY" },
  { codigo: "567", nombre: "ISLAS DE MAN" },
  { codigo: "568", nombre: "JERSEY" },
  { codigo: "888", nombre: "LOS DEMAS" },
  { codigo: "901", nombre: "COMB.Y LUBRIC." },
  { codigo: "902", nombre: "RANCHO DE NAVES" },
  { codigo: "903", nombre: "PESCA EXTRA" },
  { codigo: "904", nombre: "ORIG.O DEST. NO" },
  { codigo: "905", nombre: "ZF.IQUIQUE" },
  { codigo: "906", nombre: "DEPOSITO FRANCO" },
  { codigo: "907", nombre: "ZF.PARENAS" },
  { codigo: "910", nombre: "ZF.ARICA-ZF IND" },
  { codigo: "997", nombre: "CHILE" },
  { codigo: "998", nombre: "NAC.REPUTADA" },
  { codigo: "999", nombre: "OTROS" },
];

/** Tipos de bulto (opción 13 / CodTpoBultos). Fuente: http://comext.aduana.cl:7001/codigos/ */
export const BULTOS_ADUANA: readonly { codigo: string; nombre: string }[] = [
  { codigo: "1", nombre: "POLVO" },
  { codigo: "2", nombre: "GRANOS" },
  { codigo: "3", nombre: "NODULOS" },
  { codigo: "4", nombre: "LIQUIDO" },
  { codigo: "5", nombre: "GAS" },
  { codigo: "10", nombre: "PIEZA" },
  { codigo: "11", nombre: "TUBO" },
  { codigo: "12", nombre: "CILINDRO" },
  { codigo: "13", nombre: "ROLLO" },
  { codigo: "16", nombre: "BARRA" },
  { codigo: "17", nombre: "LINGOTE" },
  { codigo: "18", nombre: "TRONCO" },
  { codigo: "19", nombre: "BLOQUE" },
  { codigo: "20", nombre: "ROLLIZO" },
  { codigo: "21", nombre: "CAJON" },
  { codigo: "22", nombre: "CAJA DE CARTON" },
  { codigo: "23", nombre: "FARDO" },
  { codigo: "24", nombre: "BAUL" },
  { codigo: "25", nombre: "COFRE" },
  { codigo: "26", nombre: "ARMAZON" },
  { codigo: "27", nombre: "BANDEJA" },
  { codigo: "28", nombre: "CAJAMADERA" },
  { codigo: "29", nombre: "CAJALATA" },
  { codigo: "31", nombre: "BOTELLAGAS" },
  { codigo: "32", nombre: "BOTELLA" },
  { codigo: "33", nombre: "JAULA" },
  { codigo: "34", nombre: "BIDON" },
  { codigo: "35", nombre: "JABA" },
  { codigo: "36", nombre: "CESTA" },
  { codigo: "37", nombre: "BARRILETE" },
  { codigo: "38", nombre: "TONEL" },
  { codigo: "39", nombre: "PIPA" },
  { codigo: "40", nombre: "CAJANOESP" },
  { codigo: "41", nombre: "JARRO" },
  { codigo: "42", nombre: "FRASCO" },
  { codigo: "43", nombre: "DAMAJUANA" },
  { codigo: "44", nombre: "BARRIL" },
  { codigo: "45", nombre: "TAMBOR" },
  { codigo: "46", nombre: "CUNETE" },
  { codigo: "47", nombre: "TARRO" },
  { codigo: "51", nombre: "CUBO" },
  { codigo: "61", nombre: "PAQUETE" },
  { codigo: "62", nombre: "SACO" },
  { codigo: "63", nombre: "MALETA" },
  { codigo: "64", nombre: "BOLSA" },
  { codigo: "65", nombre: "BALA" },
  { codigo: "66", nombre: "RED" },
  { codigo: "67", nombre: "SOBRE" },
  { codigo: "73", nombre: "CONT20" },
  { codigo: "74", nombre: "CONT40" },
  { codigo: "75", nombre: "REEFER20" },
  { codigo: "76", nombre: "REEFER40" },
  { codigo: "77", nombre: "ESTANQUE" },
  { codigo: "78", nombre: "CONTNOESP" },
  { codigo: "80", nombre: "PALLET" },
  { codigo: "81", nombre: "TABLERO" },
  { codigo: "82", nombre: "LAMINA" },
  { codigo: "83", nombre: "CARRETE" },
  { codigo: "85", nombre: "AUTOMOTOR" },
  { codigo: "86", nombre: "ATAUD" },
  { codigo: "88", nombre: "MAQUINARIA" },
  { codigo: "89", nombre: "PLANCHA" },
  { codigo: "90", nombre: "ATADO" },
  { codigo: "91", nombre: "BOBINA" },
  { codigo: "93", nombre: "&nbsp;BULTONOESP" },
  { codigo: "98", nombre: "SIN BULTO" },
  { codigo: "99", nombre: "S/EMBALAR" },
];

/** Unidad de medida (opción 17). Fuente: http://comext.aduana.cl:7001/codigos/ */
export const UNIDADES_ADUANA: readonly { codigo: string; nombre: string }[] = [
  { codigo: "0", nombre: "S.U.M" },
  { codigo: "1", nombre: "TMB" },
  { codigo: "2", nombre: "QMB" },
  { codigo: "3", nombre: "MKWH" },
  { codigo: "4", nombre: "TMN" },
  { codigo: "5", nombre: "KLT" },
  { codigo: "6", nombre: "KN" },
  { codigo: "7", nombre: "GN" },
  { codigo: "8", nombre: "HL" },
  { codigo: "9", nombre: "LT" },
  { codigo: "10", nombre: "U" },
  { codigo: "11", nombre: "DOC" },
  { codigo: "12", nombre: "U(JGO)" },
  { codigo: "13", nombre: "MU" },
  { codigo: "14", nombre: "MT" },
  { codigo: "15", nombre: "MT2" },
  { codigo: "16", nombre: "MCUB" },
  { codigo: "17", nombre: "PAR" },
  { codigo: "18", nombre: "KNFC" },
  { codigo: "19", nombre: "CARTON" },
  { codigo: "20", nombre: "KWH" },
  { codigo: "23", nombre: "BAR" },
  { codigo: "24", nombre: "M2/1MM" },
  { codigo: "99", nombre: "S.U.M" },
];

/** Vías de transporte (opción 18 / CodViaTransp). Fuente: http://comext.aduana.cl:7001/codigos/ */
export const VIAS_ADUANA: readonly { codigo: string; nombre: string }[] = [
  { codigo: "1", nombre: "MARITIMA, FLUVIAL Y LACUSTRE" },
  { codigo: "4", nombre: "AEREO" },
  { codigo: "5", nombre: "POSTAL" },
  { codigo: "6", nombre: "FERROVIARIO" },
  { codigo: "7", nombre: "CARRETERO/TERRESTRE" },
  { codigo: "8", nombre: "OLEODUCTOS, GASODUCTOS" },
  { codigo: "9", nombre: "TENDIDO ELECTRICO (AEREO,SUBT)" },
  { codigo: "10", nombre: "OTRA" },
  { codigo: "11", nombre: "COURIER/AEREO" },
];
