/** Catálogo Puertos Aduana (opción 11). Fuente: http://comext.aduana.cl:7001/codigos/ — Anexo 51-11 / SII CodPtoEmbarque y CodPtoDesemb. */

export const PUERTOS_ADUANA: readonly { codigo: string; nombre: string }[] = [
  { codigo: "111", nombre: "MONTREAL" },
  { codigo: "112", nombre: "COSTA DEL PACIFICO" },
  { codigo: "113", nombre: "HALIFAX" },
  { codigo: "114", nombre: "VANCOUVER" },
  { codigo: "115", nombre: "SAINT JOHN" },
  { codigo: "116", nombre: "TORONTO" },
  { codigo: "117", nombre: "OTROS PUERTOS CANADA" },
  { codigo: "118", nombre: "BAYSIDE" },
  { codigo: "120", nombre: "PORT CARTIES" },
  { codigo: "121", nombre: "COSTA DEL ATLANTICO" },
  { codigo: "122", nombre: "PUERTOS DEL GOLFO ME" },
  { codigo: "123", nombre: "COSTA DEL PACIFICO" },
  { codigo: "124", nombre: "QUEBEC" },
  { codigo: "125", nombre: "PRINCE RUPERT" },
  { codigo: "126", nombre: "HAMILTON" },
  { codigo: "131", nombre: "BOSTON" },
  { codigo: "132", nombre: "NEW HAVEN" },
  { codigo: "133", nombre: "BRIDGEPORT" },
  { codigo: "134", nombre: "NEW YORK" },
  { codigo: "135", nombre: "FILADELFIA" },
  { codigo: "136", nombre: "BALTIMORE" },
  { codigo: "137", nombre: "NORFOLK" },
  { codigo: "139", nombre: "CHARLESTON" },
  { codigo: "140", nombre: "SAVANAH" },
  { codigo: "141", nombre: "MIAMI" },
  { codigo: "142", nombre: "EVERGLADES" },
  { codigo: "143", nombre: "JACKSONVILLE" },
  { codigo: "145", nombre: "PALM BEACH" },
  { codigo: "146", nombre: "BATON ROUGE" },
  { codigo: "147", nombre: "COLUMBRES" },
  { codigo: "148", nombre: "PITTSBURGH" },
  { codigo: "149", nombre: "DULUTH" },
  { codigo: "150", nombre: "MILWAUKEE" },
  { codigo: "151", nombre: "TAMPA" },
  { codigo: "152", nombre: "PENSACOLA" },
  { codigo: "153", nombre: "MOBILE" },
  { codigo: "154", nombre: "NEW ORLEANS" },
  { codigo: "155", nombre: "PORT ARTHUR" },
  { codigo: "156", nombre: "GALVESTON" },
  { codigo: "157", nombre: "CORPUS CRISTI" },
  { codigo: "158", nombre: "BROWNSVILLE" },
  { codigo: "159", nombre: "HOUSTON" },
  { codigo: "160", nombre: "OAKLAND" },
  { codigo: "161", nombre: "STOCKTON" },
  { codigo: "171", nombre: "SEATTLE" },
  { codigo: "172", nombre: "PORTLAND" },
  { codigo: "173", nombre: "SAN FRANCISCO" },
  { codigo: "174", nombre: "LOS ANGELES" },
  { codigo: "175", nombre: "LONG BEACH" },
  { codigo: "176", nombre: "SAN DIEGO" },
  { codigo: "180", nombre: "OTROS PUERTOS EE.UU." },
  { codigo: "199", nombre: "LOS VILOS" },
  { codigo: "204", nombre: "PATACHE" },
  { codigo: "205", nombre: "CALBUCO" },
  { codigo: "206", nombre: "MICHILLA" },
  { codigo: "207", nombre: "PUERTO ANGAMOS" },
  { codigo: "208", nombre: "POSEIDON" },
  { codigo: "209", nombre: "TRES PUENTES" },
  { codigo: "210", nombre: "OTROS PUERTOS MEXICO" },
  { codigo: "211", nombre: "TAMPICO" },
  { codigo: "212", nombre: "COSTA DEL PACIFICO" },
  { codigo: "213", nombre: "VERACRUZ" },
  { codigo: "214", nombre: "COATZACOALCOS" },
  { codigo: "215", nombre: "GUAYMAS" },
  { codigo: "216", nombre: "MAZATLAN" },
  { codigo: "217", nombre: "MANZANILLO" },
  { codigo: "218", nombre: "ACAPULCO" },
  { codigo: "219", nombre: "GOLFO DE MEXICO,OTRO" },
  { codigo: "220", nombre: "ALTAMIRA" },
  { codigo: "221", nombre: "CRISTOBAL" },
  { codigo: "222", nombre: "BALBOA" },
  { codigo: "223", nombre: "COLON" },
  { codigo: "224", nombre: "OTROS PTOS. PANAMA" },
  { codigo: "231", nombre: "OTROS PTOS. COLOMBIA" },
  { codigo: "232", nombre: "BUENAVENTURA" },
  { codigo: "233", nombre: "BARRANQUILLA" },
  { codigo: "241", nombre: "OTROS PTOS. ECUADOR" },
  { codigo: "242", nombre: "GUAYAQUIL" },
  { codigo: "251", nombre: "OTROS PTOS. DE PERU" },
  { codigo: "252", nombre: "CALLAO" },
  { codigo: "253", nombre: "ILO" },
  { codigo: "254", nombre: "IQUITOS" },
  { codigo: "261", nombre: "OTROS PTOS.ARGENTINA" },
  { codigo: "262", nombre: "BUENOS AIRES" },
  { codigo: "263", nombre: "NECOCHEA" },
  { codigo: "264", nombre: "MENDOZA" },
  { codigo: "265", nombre: "CORDOBA" },
  { codigo: "266", nombre: "BAHIA BLANCA" },
  { codigo: "267", nombre: "COMODORO RIVADAVIA" },
  { codigo: "268", nombre: "PUERTO MADRYN" },
  { codigo: "269", nombre: "MAR DEL PLATA" },
  { codigo: "270", nombre: "ROSARIO" },
  { codigo: "271", nombre: "OTROS PTOS.URUGUAY" },
  { codigo: "272", nombre: "MONTEVIDEO" },
  { codigo: "281", nombre: "OTROS PTOS.VENEZUELA" },
  { codigo: "282", nombre: "LA GUAIRA" },
  { codigo: "285", nombre: "MARACAIBO" },
  { codigo: "291", nombre: "OTROS PTOS.BRASIL" },
  { codigo: "292", nombre: "SANTOS" },
  { codigo: "293", nombre: "RIO DE JANEIRO" },
  { codigo: "294", nombre: "RIO GRANDE DEL SUR" },
  { codigo: "295", nombre: "PARANAGUA" },
  { codigo: "296", nombre: "SAO PAULO" },
  { codigo: "297", nombre: "SALVADOR" },
  { codigo: "301", nombre: "OTROS ANT.HOLANDESA" },
  { codigo: "302", nombre: "CURAZAO" },
  { codigo: "399", nombre: "OTROS PTOS.AMERICA" },
  { codigo: "411", nombre: "SHANGAI" },
  { codigo: "412", nombre: "DAIREN" },
  { codigo: "413", nombre: "OTROS PTOS.DE CHINA" },
  { codigo: "420", nombre: "OTROS PUERT COREA N" },
  { codigo: "421", nombre: "NAMPO" },
  { codigo: "422", nombre: "BUSAN" },
  { codigo: "423", nombre: "OTROS PTOS. COREA S" },
  { codigo: "431", nombre: "MANILA" },
  { codigo: "432", nombre: "OTROS PTOS.FILIPINAS" },
  { codigo: "441", nombre: "OTROS PTOS.JAPONESES" },
  { codigo: "442", nombre: "OSAKA" },
  { codigo: "443", nombre: "KOBE" },
  { codigo: "444", nombre: "YOKOHAMA" },
  { codigo: "445", nombre: "NAGOYA" },
  { codigo: "446", nombre: "SHIMIZUI" },
  { codigo: "447", nombre: "MOJI" },
  { codigo: "448", nombre: "YAWATA" },
  { codigo: "449", nombre: "FUKUYAMA" },
  { codigo: "451", nombre: "KAOHSIUNG" },
  { codigo: "452", nombre: "KEELUNG" },
  { codigo: "453", nombre: "OTROS PTOS.TAIWAN" },
  { codigo: "461", nombre: "KARHG ISLAND" },
  { codigo: "462", nombre: "OTROS PTO.IRAN NO ES" },
  { codigo: "471", nombre: "CALCUTA" },
  { codigo: "472", nombre: "OTROS PTOS. DE INDIA" },
  { codigo: "481", nombre: "CHALNA" },
  { codigo: "482", nombre: "OTROS PTO.BANGLADESH" },
  { codigo: "491", nombre: "OTROS PTO.SINGAPURE" },
  { codigo: "492", nombre: "HONG KONG" },
  { codigo: "499", nombre: "OTROS PTO.ASIATICOS" },
  { codigo: "511", nombre: "CONSTANZA" },
  { codigo: "512", nombre: "OTROS PTO.DE RUMANIA" },
  { codigo: "521", nombre: "VARNA" },
  { codigo: "522", nombre: "OTROS PTOS BULGARIA" },
  { codigo: "533", nombre: "BELGRADO" },
  { codigo: "534", nombre: "OTROS PUERTOS DE SER" },
  { codigo: "535", nombre: "PODGORITSA" },
  { codigo: "536", nombre: "OTROS PUERTOS DE MON" },
  { codigo: "537", nombre: "OTROS PUERTOS DE CRO" },
  { codigo: "538", nombre: "RIJEKA" },
  { codigo: "541", nombre: "OTROS PTOS.DE ITALIA" },
  { codigo: "542", nombre: "GENOVA" },
  { codigo: "543", nombre: "LIORNA,LIVORNO" },
  { codigo: "544", nombre: "NAPOLES" },
  { codigo: "545", nombre: "SALERNO" },
  { codigo: "546", nombre: "AUGUSTA" },
  { codigo: "547", nombre: "SAVONA" },
  { codigo: "551", nombre: "OTROS PTOS.FRANCIA" },
  { codigo: "552", nombre: "LA PALLICE" },
  { codigo: "553", nombre: "LE HAVRE" },
  { codigo: "554", nombre: "MARSELLA" },
  { codigo: "555", nombre: "BURDEOS" },
  { codigo: "556", nombre: "CALAIS" },
  { codigo: "557", nombre: "BREST" },
  { codigo: "558", nombre: "RUAN" },
  { codigo: "561", nombre: "OTROS PTOS.ESPANA" },
  { codigo: "562", nombre: "CADIZ" },
  { codigo: "563", nombre: "BARCELONA" },
  { codigo: "564", nombre: "BILBAO" },
  { codigo: "565", nombre: "HUELVA" },
  { codigo: "566", nombre: "SEVILLA" },
  { codigo: "567", nombre: "TARRAGONA" },
  { codigo: "568", nombre: "ALGECIRAS" },
  { codigo: "569", nombre: "VALENCIA" },
  { codigo: "571", nombre: "LIVERPOOL" },
  { codigo: "572", nombre: "LONDRES" },
  { codigo: "573", nombre: "ROCHESTER" },
  { codigo: "574", nombre: "ETEN SALVERRY" },
  { codigo: "576", nombre: "OTROS PTOS.INGLATERR" },
  { codigo: "577", nombre: "DOVER" },
  { codigo: "578", nombre: "PLYMOUTH" },
  { codigo: "581", nombre: "HELSINKI" },
  { codigo: "582", nombre: "OTROS PTOS.FINLANDIA" },
  { codigo: "583", nombre: "HANKO" },
  { codigo: "584", nombre: "KEMI" },
  { codigo: "585", nombre: "KOKKOLA" },
  { codigo: "586", nombre: "KOTKA" },
  { codigo: "587", nombre: "OULO" },
  { codigo: "588", nombre: "PIETARSAARI" },
  { codigo: "589", nombre: "PORI" },
  { codigo: "591", nombre: "BREMEN" },
  { codigo: "592", nombre: "HAMBURGO" },
  { codigo: "593", nombre: "NUREMBERG" },
  { codigo: "594", nombre: "FRANKFURT" },
  { codigo: "595", nombre: "DUSSELDORF" },
  { codigo: "596", nombre: "OTROS PTOS.ALEMANIA" },
  { codigo: "597", nombre: "CUXHAVEN" },
  { codigo: "598", nombre: "ROSTOCK" },
  { codigo: "599", nombre: "OLDENBURG" },
  { codigo: "601", nombre: "AMBERES" },
  { codigo: "602", nombre: "OTROS PTO.BELGICA" },
  { codigo: "603", nombre: "ZEEBRUGGE" },
  { codigo: "604", nombre: "GHENT" },
  { codigo: "605", nombre: "OOSTENDE" },
  { codigo: "611", nombre: "LISBOA" },
  { codigo: "612", nombre: "OTROSS PTOS.PORTUGAL" },
  { codigo: "613", nombre: "SETUBAL" },
  { codigo: "621", nombre: "AMSTERDAM" },
  { codigo: "622", nombre: "ROTTERDAM" },
  { codigo: "623", nombre: "OTROS PTOS.HOLANDA" },
  { codigo: "631", nombre: "GOTEMBURGO" },
  { codigo: "632", nombre: "OTROS PTOS.SUECIA" },
  { codigo: "633", nombre: "MALMO" },
  { codigo: "634", nombre: "HELSIMBORG" },
  { codigo: "635", nombre: "KALMAR" },
  { codigo: "641", nombre: "AARHUS" },
  { codigo: "642", nombre: "COPENHAGEN" },
  { codigo: "643", nombre: "OTROS PTOS.DINAMARCA" },
  { codigo: "644", nombre: "AALBORG" },
  { codigo: "645", nombre: "ODENSE" },
  { codigo: "651", nombre: "OSLO" },
  { codigo: "652", nombre: "OTROS PTO. NORUEGA" },
  { codigo: "653", nombre: "STAVANGER" },
  { codigo: "699", nombre: "OTROS PTOS.EUROPA" },
  { codigo: "711", nombre: "DURBAM" },
  { codigo: "712", nombre: "CIUDAD DEL CABO" },
  { codigo: "713", nombre: "OTROS PTO.SUDAFFRICA" },
  { codigo: "714", nombre: "SALDANHA" },
  { codigo: "715", nombre: "PORT-ELIZABETH" },
  { codigo: "716", nombre: "MOSSEL-BAY" },
  { codigo: "717", nombre: "EAST-LONDON" },
  { codigo: "799", nombre: "OTROS PTO.DE AFRICA" },
  { codigo: "811", nombre: "SIDNEY" },
  { codigo: "812", nombre: "FREMANTLE" },
  { codigo: "813", nombre: "OTROS PTOS.AUSTRALIA" },
  { codigo: "814", nombre: "ADELAIDA" },
  { codigo: "815", nombre: "DARWIN" },
  { codigo: "816", nombre: "GERALDTON" },
  { codigo: "817", nombre: "PUERTO CABO FROWARD" },
  { codigo: "818", nombre: "HUACHIPATO" },
  { codigo: "819", nombre: "ESCUADRON" },
  { codigo: "820", nombre: "TERQUIM" },
  { codigo: "821", nombre: "ESPERANZA" },
  { codigo: "822", nombre: "TERMINAL ENAEX" },
  { codigo: "823", nombre: "TNAL. OXIQUIM" },
  { codigo: "824", nombre: "PASO BUTAMALLIN" },
  { codigo: "825", nombre: "AE.LA ARAUCANIA" },
  { codigo: "826", nombre: "E.MEDICION RECI" },
  { codigo: "827", nombre: "T.GNELES NORTE" },
  { codigo: "828", nombre: "MUELLE INTERACID TRA" },
  { codigo: "831", nombre: "AERÓDROMO PICHOY" },
  { codigo: "899", nombre: "OTROS PTOS. OCEANIA" },
  { codigo: "900", nombre: "RANCHO,COMB.,LUBRIC." },
  { codigo: "901", nombre: "ARICA" },
  { codigo: "902", nombre: "IQUIQUE" },
  { codigo: "903", nombre: "ANTOFAGASTA" },
  { codigo: "904", nombre: "COQUIMBO" },
  { codigo: "905", nombre: "VALPARAISO" },
  { codigo: "906", nombre: "SAN ANTONIO" },
  { codigo: "907", nombre: "TALCAHUANO" },
  { codigo: "908", nombre: "SAN VICENTE" },
  { codigo: "909", nombre: "LIRQUEN" },
  { codigo: "910", nombre: "PUERTO MONTT" },
  { codigo: "911", nombre: "CHACABUCO/PTO.AYSEN" },
  { codigo: "912", nombre: "PUNTA ARENAS" },
  { codigo: "913", nombre: "PATILLOS" },
  { codigo: "914", nombre: "TOCOPILLA" },
  { codigo: "915", nombre: "MEJILLONES" },
  { codigo: "916", nombre: "TALTAL" },
  { codigo: "917", nombre: "CHANARAL/BARQUITO" },
  { codigo: "918", nombre: "CALDERA" },
  { codigo: "919", nombre: "CALDERILLA" },
  { codigo: "920", nombre: "HUASCO/GUACOLDA" },
  { codigo: "921", nombre: "QUINTERO" },
  { codigo: "922", nombre: "JUAN FERNANDEZ" },
  { codigo: "923", nombre: "CONSTITUCION" },
  { codigo: "924", nombre: "TOME" },
  { codigo: "925", nombre: "PENCO" },
  { codigo: "926", nombre: "CORONEL" },
  { codigo: "927", nombre: "LOTA" },
  { codigo: "928", nombre: "LEBU" },
  { codigo: "929", nombre: "ISLA DE PASCUA" },
  { codigo: "930", nombre: "CORRAL" },
  { codigo: "931", nombre: "ANCUD" },
  { codigo: "932", nombre: "CASTRO" },
  { codigo: "933", nombre: "QUELLON" },
  { codigo: "934", nombre: "CHAITEN" },
  { codigo: "935", nombre: "TORTEL" },
  { codigo: "936", nombre: "NATALES" },
  { codigo: "937", nombre: "GUARELLO" },
  { codigo: "938", nombre: "PUERTO ANDINO" },
  { codigo: "939", nombre: "PERCY" },
  { codigo: "940", nombre: "CLARENCIA" },
  { codigo: "941", nombre: "GREGORIO" },
  { codigo: "942", nombre: "CABO NEGRO" },
  { codigo: "943", nombre: "PUERTO WILLIAMS" },
  { codigo: "944", nombre: "TER.ANTARTICO CHILEN" },
  { codigo: "945", nombre: "AEROP. CARRIEL SUR" },
  { codigo: "946", nombre: "GUAYACAN" },
  { codigo: "947", nombre: "PASO PEHUENCHE" },
  { codigo: "948", nombre: "VENTANAS" },
  { codigo: "949", nombre: "PINO HACHADO(LIUCURA" },
  { codigo: "950", nombre: "CALETA COLOSO" },
  { codigo: "951", nombre: "AGUAS NEGRAS" },
  { codigo: "952", nombre: "ZONA FRANCA IQUIQUE" },
  { codigo: "953", nombre: "ZONA FRANCA PTA AREN" },
  { codigo: "954", nombre: "RIO MAYER" },
  { codigo: "955", nombre: "RIO MOSCO" },
  { codigo: "956", nombre: "VISVIRI" },
  { codigo: "957", nombre: "CHACALLUTA" },
  { codigo: "958", nombre: "CHUNGARA" },
  { codigo: "959", nombre: "COLCHANE" },
  { codigo: "960", nombre: "ABRA DE NAPA" },
  { codigo: "961", nombre: "OLLAGUE" },
  { codigo: "962", nombre: "SAN PEDRO DE ATACAMA" },
  { codigo: "963", nombre: "SOCOMPA" },
  { codigo: "964", nombre: "SAN FRANCISCO" },
  { codigo: "965", nombre: "LOS LIBERTADORES" },
  { codigo: "966", nombre: "MAHUIL MALAL" },
  { codigo: "967", nombre: "CARDENAL SAMORE" },
  { codigo: "968", nombre: "PEREZ ROSALES" },
  { codigo: "969", nombre: "FUTALEUFU" },
  { codigo: "970", nombre: "PALENA-CARRENLEUFU" },
  { codigo: "971", nombre: "PANGUIPULLI" },
  { codigo: "972", nombre: "HUAHUM" },
  { codigo: "973", nombre: "LAGO VERDE" },
  { codigo: "974", nombre: "APPELEG" },
  { codigo: "975", nombre: "PAMPA ALTA" },
  { codigo: "976", nombre: "HUEMULES" },
  { codigo: "977", nombre: "CHILE CHICO" },
  { codigo: "978", nombre: "BAKER" },
  { codigo: "979", nombre: "DOROTEA" },
  { codigo: "980", nombre: "CASAS VIEJAS" },
  { codigo: "981", nombre: "MONTE AYMOND" },
  { codigo: "982", nombre: "SAN SEBASTIAN" },
  { codigo: "983", nombre: "COYHAIQUE ALTO" },
  { codigo: "984", nombre: "TRIANA" },
  { codigo: "985", nombre: "IBANEZ PALAVICINI" },
  { codigo: "986", nombre: "VILLA OHIGGINS" },
  { codigo: "987", nombre: "AEROP.CHACALLUTA" },
  { codigo: "988", nombre: "AEROP.DIEGO ARACENA" },
  { codigo: "989", nombre: "AEROP.CERRO MORENO" },
  { codigo: "990", nombre: "AEROP.EL TEPUAL" },
  { codigo: "991", nombre: "AEROP.C.I.DEL CAMPO" },
  { codigo: "992", nombre: "AEROP.A.M.BENITEZ" },
  { codigo: "993", nombre: "AEROD. EL LOA" },
  { codigo: "994", nombre: "ARICA-TACNA" },
  { codigo: "995", nombre: "ARICA-LA PAZ" },
  { codigo: "997", nombre: "OTROS PTOS. CHILENOS" },
  { codigo: "998", nombre: "PASO JAMA" },
  { codigo: "999", nombre: "GNL MEJILLONES" },
];
